backend:
  name: git-gateway
  branch: main
media_folder: public/assets
public_folder: /assets
publish_mode: editorial_workflow

collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - label: 'Home'
        name: 'home'
        file: 'pages/content/home.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Publish Date', name: 'date', widget: 'datetime' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
          # - label: 'Items'
          #   name: 'items'
          #   widget: list
          #   fields:
          #     - { label: 'Name', name: 'name', widget: 'string' }
          #     - { label: 'Description', name: 'description', widget: 'text' }
  - name: 'tags'
    label: 'Tags'
    file: 'meta/tags.yml'
    description: 'List of tags'
    fields:
      - name: tags
        label: Tags
        label_singular: 'Tag'
        widget: list
        fields:
          - label: 'Slug'
            name: 'slug'
            widget: 'string'
            hint: 'The part of a URL identifies the tag'
          - label: 'Display Name'
            name: 'name'
            widget: 'string'
            hint: 'Tag name for displaying on the site'
  - name: 'posts'
    label: 'Posts'
    label_singular: 'Post'
    folder: 'pages/articles/'
    extension: mdx
    format: frontmatter
    create: true
    slug: '{{slug}}'
    identifier_field: slug
    summary: '{{title}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'datetime',
          format: 'YYYY-MM-DD',
          dateFormat: 'YYYY-MM-DD',
          timeFormat: false,
        }
      - { label: 'Featured Image', name: 'thumbnail', widget: 'image' }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
