local_backend: true

backend:
  name: git-gateway
  branch: main
media_folder: public/assets
public_folder: /assets
publish_mode: editorial_workflow

collections:
  - name: 'config'
    label: 'Config'
    delete: false
    editor:
      preview: false
    files:
      - name: 'general'
        label: 'Site Config'
        file: 'config.json'
        description: 'General site settings'
        fields:
          - label: 'URL'
            name: 'base_url'
            widget: 'string'
            hint: 'Do not enter the trailing slash of the URL'
          - label: 'Site title'
            name: 'site_title'
            widget: 'string'
          - label: 'Site description'
            name: 'site_description'
            widget: 'string'
          - label: 'Site keywords'
            name: 'site_keywords'
            widget: 'list'
            summary: '{{fields.keyword.keyword}}'
            field: { label: 'Keyword', name: 'keyword', widget: 'string' }
          - label: 'Twitter account'
            name: 'twitter_account'
            widget: 'string'
          - label: 'GitHub account'
            name: 'github_account'
            widget: 'string'

  - name: 'meta'
    label: 'Meta'
    delete: false
    editor:
      preview: false
    files:
      - name: 'tags'
        label: 'Tags'
        file: 'meta/tags.yml'
        description: 'List of tags'
        fields:
          - name: tags
            label: Tags
            label_singular: 'Tag'
            widget: list
            fields:
              - {
                  label: 'Slug',
                  name: 'slug',
                  widget: 'string',
                  hint: 'The part of a URL identifies the tag',
                }
              - {
                  label: 'Display Name',
                  name: 'name',
                  widget: 'string',
                  hint: 'Tag name for displaying on the site',
                }
      - name: 'locations'
        label: 'Locations'
        file: 'meta/locations.yml'
        description: 'List of locations'
        fields:
          - name: locations
            label: Locations
            label_singular: 'Location'
            widget: list
            fields:
              - {
                  label: 'Slug',
                  name: 'slug',
                  widget: 'string',
                  hint: 'The part of a URL identifies the tag',
                }
              - {
                  label: 'Display Name',
                  name: 'name',
                  widget: 'string',
                  hint: 'Tag name for displaying on the site',
                }
  - name: 'posts'
    label: 'Posts'
    label_singular: 'Post'
    folder: 'content/posts/'
    extension: mdx
    format: frontmatter
    create: true
    slug: '{{slug}}'
    identifier_field: slug
    summary: '{{title}}'
    fields:
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Description'
        name: 'description'
        widget: 'text'
      - label: 'Publish Date'
        name: 'date'
        widget: 'datetime'
        format: 'YYYY-MM-DD'
        dateFormat: 'YYYY-MM-DD'
        timeFormat: false
      - label: 'Locations'
        name: 'locations'
        widget: list
        summary: '{{fields.location}}'
        fields:
          - {
              label: 'Location',
              name: 'location',
              widget: 'relation',
              collection: 'meta',
              file: 'location',
              searchFields: 'locations.*.name',
              displayFields: 'locations.*.name',
              valueField: 'locations.*.slug',
            }
      - label: 'Featured Image'
        name: 'thumbnail'
        widget: 'image'
      - label: 'Tags'
        label_singular: 'Tag'
        name: 'tags'
        widget: list
        summary: '{{fields.tag}}'
        fields:
          - {
              label: 'Tag',
              name: 'tag',
              widget: 'relation',
              collection: 'meta',
              file: 'tags',
              searchFields: 'tags.*.name',
              displayFields: 'tags.*.name',
              valueField: 'tags.*.slug',
            }
      - label: 'Body'
        name: 'body'
        widget: 'markdown'
